-- DDL PostgreSQL del modulo de ingreso de denuncias/partes.
-- Requiere las tablas existentes: Usuarios, UnidadesEjecutoras y Dependencias.

CREATE TABLE IF NOT EXISTS denuncia (
    id_sgsp BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    version VARCHAR(20) NOT NULL DEFAULT '1.0', control_calidad BOOLEAN NOT NULL DEFAULT FALSE,
    nro_formulario VARCHAR(50), id_modo_denuncia INTEGER NOT NULL DEFAULT 1 CHECK (id_modo_denuncia BETWEEN 0 AND 4), moneda_avalua INTEGER NOT NULL DEFAULT 0,
    monto_avaluado NUMERIC(14,2) NOT NULL DEFAULT 0 CHECK (monto_avaluado >= 0),
    requiere_investigacion BOOLEAN NOT NULL DEFAULT FALSE, resenna_policial TEXT,
    fecha_seguimiento_area_investigaciones TIMESTAMPTZ, fecha_seguimiento_area_seguridad TIMESTAMPTZ,
    estado VARCHAR(20) NOT NULL DEFAULT 'Borrador' CHECK (estado IN ('Borrador','Enviada','Anulada','Cerrada')),
    modo_denuncia VARCHAR(30) NOT NULL DEFAULT 'ingreso', creado_por VARCHAR(50) NOT NULL REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT,
    fecha_creacion TIMESTAMPTZ NOT NULL DEFAULT now(), fecha_actualizacion TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS denuncia_tipo_arma (
    id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    id_arma BIGINT GENERATED BY DEFAULT AS IDENTITY, descripcion VARCHAR(150) NOT NULL,
    PRIMARY KEY (id_sgsp, id_arma)
);
CREATE TABLE IF NOT EXISTS denuncia_hecho_aclarado (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    denuncias_aclaradas BOOLEAN NOT NULL DEFAULT FALSE, derivado_de_id INTEGER, derivado_de_descripcion VARCHAR(255),
    consecuencia_id INTEGER, consecuencia_descripcion VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS denuncia_informacion_complementaria (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    enviar_parte BOOLEAN NOT NULL DEFAULT FALSE, enviar_juzgado BOOLEAN NOT NULL DEFAULT FALSE,
    enviar_fiscalia BOOLEAN NOT NULL DEFAULT FALSE, reservar_denuncia BOOLEAN NOT NULL DEFAULT TRUE,
    impacto_publico_institucional BOOLEAN NOT NULL DEFAULT FALSE, drogas_involucradas BOOLEAN NOT NULL DEFAULT FALSE,
    boca_desarticulada BOOLEAN NOT NULL DEFAULT FALSE, cant_boca_desarticulada INTEGER CHECK (cant_boca_desarticulada IS NULL OR cant_boca_desarticulada >= 0),
    armas_fuego_involucradas BOOLEAN NOT NULL DEFAULT FALSE, allanamiento BOOLEAN
);
CREATE TABLE IF NOT EXISTS denuncia_autoridad_interviniente (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    seguimiento_area_seguridad BOOLEAN NOT NULL DEFAULT FALSE, seguimiento_area_investigaciones BOOLEAN NOT NULL DEFAULT FALSE,
    policia_intervino BOOLEAN NOT NULL DEFAULT FALSE, policia_caminera_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    emergencia_movil_intervino BOOLEAN NOT NULL DEFAULT FALSE, bombero_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    policia_tecnica_intervino BOOLEAN NOT NULL DEFAULT FALSE, autoridades_judiciales_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    inspectores_municipales_intervino BOOLEAN NOT NULL DEFAULT FALSE, ejercito_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    fiscalia_intervino BOOLEAN NOT NULL DEFAULT FALSE, policia_aerea_nacional_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    prefectura_naval_intervino BOOLEAN NOT NULL DEFAULT FALSE, fuerza_aerea_uruguaya_intervino BOOLEAN NOT NULL DEFAULT FALSE,
    aduanas_intervino BOOLEAN NOT NULL DEFAULT FALSE, dn_seguridad_rural_intervino BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS denuncia_multimedia (
    id_multimedia BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL, tipo VARCHAR(100) NOT NULL, tamano BIGINT NOT NULL DEFAULT 0 CHECK (tamano >= 0), ruta_storage TEXT, fecha_carga TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE TABLE IF NOT EXISTS denuncia_datos_sippau (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, id_sippau BIGINT
);
CREATE TABLE IF NOT EXISTS denuncia_sippau_caso (
    id_caso BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    nunc BIGINT, nro_caso BIGINT, estado_id INTEGER, estado_descripcion VARCHAR(150), usuario VARCHAR(50), fecha TIMESTAMPTZ
);
CREATE TABLE IF NOT EXISTS denuncia_sippau_orden_policial (
    id_orden BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, datos JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS denuncia_sippau_orden_respuesta (
    id_respuesta BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, datos JSONB NOT NULL DEFAULT '{}'::jsonb
);
CREATE TABLE IF NOT EXISTS denuncia_datos_sivve (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, id_sivve BIGINT, ingresada_por VARCHAR(50)[] NOT NULL DEFAULT '{}',
    fecha_hora TIMESTAMPTZ, fecha_ejecucion TIMESTAMPTZ, confirmada_sivve BOOLEAN NOT NULL DEFAULT FALSE, narracion_sivve TEXT
);
CREATE TABLE IF NOT EXISTS denuncia_web (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, ingresada_online BOOLEAN NOT NULL DEFAULT FALSE,
    estado VARCHAR(50), id_sdl_denuncia VARCHAR(100), denunciante_recibe_mail BOOLEAN, con_firma BOOLEAN
);

CREATE TABLE IF NOT EXISTS denuncia_ubicacion (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL UNIQUE REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, dia_hora_conocimiento TIMESTAMPTZ NOT NULL,
    fecha_hecho_desde TIMESTAMPTZ NOT NULL, fecha_hecho_hasta TIMESTAMPTZ, es_feriado BOOLEAN NOT NULL DEFAULT FALSE,
    id_uuee INTEGER NOT NULL REFERENCES "UnidadesEjecutoras" ("IdUuee") ON DELETE RESTRICT,
    id_dependencia INTEGER NOT NULL REFERENCES "Dependencias" ("IdDependencia") ON DELETE RESTRICT,
    calle VARCHAR(150), numero VARCHAR(30), esquina1 VARCHAR(150), esquina2 VARCHAR(150), bis BOOLEAN NOT NULL DEFAULT FALSE,
    padron VARCHAR(50), segmento VARCHAR(50), barrio_paraje VARCHAR(150), block VARCHAR(50), senda VARCHAR(100), apartamento VARCHAR(50),
    localidad VARCHAR(150), departamento VARCHAR(100), direccion_extranjera BOOLEAN NOT NULL DEFAULT FALSE, pais VARCHAR(100),
    direccion_extranjera_completa TEXT, telefono VARCHAR(30), ruta VARCHAR(100), kilometro NUMERIC(10,3), balneario VARCHAR(100), barrio VARCHAR(100),
    id_tipo_lugar INTEGER, jurisdiccion_id INTEGER, jurisdiccion_descripcion VARCHAR(150), id_lugar INTEGER, coordenada_x NUMERIC(12,8), coordenada_y NUMERIC(12,8)
);
CREATE TABLE IF NOT EXISTS tipificacion_clasificacion (
    id_clasificacion INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    tipo_denuncia VARCHAR(50) NOT NULL CHECK (tipo_denuncia IN ('Crimen','DelitoFalta','HechoPolicial','Accidente')),
    nombre VARCHAR(255) NOT NULL, id_clasificacion_padre INTEGER REFERENCES tipificacion_clasificacion (id_clasificacion) ON DELETE RESTRICT,
    habilitada BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE (tipo_denuncia, nombre)
);
CREATE TABLE IF NOT EXISTS tipificacion_complemento (
    id_complemento INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_clasificacion INTEGER NOT NULL REFERENCES tipificacion_clasificacion (id_clasificacion) ON DELETE CASCADE,
    nombre VARCHAR(255) NOT NULL, habilitado BOOLEAN NOT NULL DEFAULT TRUE, UNIQUE (id_clasificacion, nombre)
);
CREATE TABLE IF NOT EXISTS denuncia_tipificacion (
    id_sgsp BIGINT PRIMARY KEY REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, tipo_denuncia VARCHAR(50) NOT NULL CHECK (tipo_denuncia IN ('Crimen','DelitoFalta','HechoPolicial','Accidente')),
    id_clasificacion INTEGER NOT NULL REFERENCES tipificacion_clasificacion (id_clasificacion) ON DELETE RESTRICT,
    id_complemento INTEGER REFERENCES tipificacion_complemento (id_complemento) ON DELETE RESTRICT,
    id_modalidad INTEGER, id_gravedad INTEGER, tentativa BOOLEAN NOT NULL DEFAULT FALSE, juzgados_utilizados JSONB NOT NULL DEFAULT '[]'::jsonb
);

CREATE TABLE IF NOT EXISTS denuncia_interviniente (
    id_interviniente BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    id_caracter INTEGER NOT NULL, descripcion_caracter VARCHAR(100) NOT NULL, id_vehiculo BIGINT, fecha_fallecido TIMESTAMPTZ, fecha_detenido TIMESTAMPTZ,
    id_circunstancia_detencion INTEGER, relacion_indagado JSONB, convivencia BOOLEAN NOT NULL DEFAULT FALSE, espirometria JSONB, espirometria_droga JSONB,
    cheq_dnic BOOLEAN NOT NULL DEFAULT FALSE, fecha_cheq_dnic TIMESTAMPTZ, id_digital BOOLEAN NOT NULL DEFAULT FALSE, medidas_coercion JSONB NOT NULL DEFAULT '[]'::jsonb,
    lesion JSONB, escolaridad JSONB, esta_en_violencia_domestica BOOLEAN NOT NULL DEFAULT FALSE, es_persona_ausente BOOLEAN NOT NULL DEFAULT FALSE
);
CREATE TABLE IF NOT EXISTS interviniente_datos_personales (
    id_interviniente BIGINT PRIMARY KEY REFERENCES denuncia_interviniente (id_interviniente) ON DELETE CASCADE,
    primer_nombre VARCHAR(100), primer_apellido VARCHAR(100), segundo_nombre VARCHAR(100), segundo_apellido VARCHAR(100), id_tipo_documento INTEGER, cedula VARCHAR(20),
    id_origen_di INTEGER, id_nacionalidad INTEGER REFERENCES "Nacionalidades" ("IdNacionalidad") ON DELETE RESTRICT, sexo VARCHAR(30), fecha_nacimiento DATE, edad INTEGER CHECK (edad IS NULL OR edad >= 0), correo_electronico VARCHAR(150), celular VARCHAR(30),
    id_ocupacion INTEGER, id_estado_civil INTEGER REFERENCES "EstadosCiviles" ("IdEstadoCivil") ON DELETE RESTRICT, id_escolaridad INTEGER, situacion JSONB, madre VARCHAR(200), padre VARCHAR(200), pasaporte VARCHAR(50), credencial VARCHAR(50), lugar_nacimiento VARCHAR(150),
    firma TEXT, tiene_requisitoria BOOLEAN NOT NULL DEFAULT FALSE, tiene_medidas_cautelares BOOLEAN NOT NULL DEFAULT FALSE, tiene_averiguacion_paradero BOOLEAN NOT NULL DEFAULT FALSE,
    tiene_evento_ausencia BOOLEAN NOT NULL DEFAULT FALSE, tiene_alerta_amber BOOLEAN NOT NULL DEFAULT FALSE, foto TEXT, nombre_completo VARCHAR(250), antecedentes TEXT, anotaciones_menor TEXT,
    nro_prontuario VARCHAR(50), comp_prontuario VARCHAR(50), nombre_en_cedula VARCHAR(250)
);
CREATE TABLE IF NOT EXISTS interviniente_domicilio (
    id_interviniente BIGINT PRIMARY KEY REFERENCES denuncia_interviniente (id_interviniente) ON DELETE CASCADE, calle VARCHAR(150), numero VARCHAR(30), esquina1 VARCHAR(150), esquina2 VARCHAR(150),
    bis BOOLEAN NOT NULL DEFAULT FALSE, padron VARCHAR(50), segmento VARCHAR(50), barrio_paraje VARCHAR(150), block VARCHAR(50), senda VARCHAR(100), apartamento VARCHAR(50), localidad JSONB, departamento JSONB,
    direccion_extranjera BOOLEAN NOT NULL DEFAULT FALSE, pais JSONB, direccion_extranjera_completa TEXT, telefono_particular VARCHAR(30), telefono_celular VARCHAR(30), observaciones TEXT,
    ruta VARCHAR(100), kilometro NUMERIC(10,3), balneario VARCHAR(100), barrio VARCHAR(100), id_domicilio BIGINT, id_tipo_lugar INTEGER, jurisdiccion JSONB, manzana VARCHAR(50), telefono VARCHAR(30), tipo_ubicacion VARCHAR(100), id_lugar INTEGER, coordenada_x NUMERIC(12,8), coordenada_y NUMERIC(12,8)
);
CREATE TABLE IF NOT EXISTS interviniente_policia (
    id_interviniente BIGINT PRIMARY KEY REFERENCES denuncia_interviniente (id_interviniente) ON DELETE CASCADE, id_policia_actuante VARCHAR(50), grado_operador JSONB, jefatura JSONB, seccional JSONB,
    id_caracter INTEGER, toma_la_denuncia BOOLEAN NOT NULL DEFAULT FALSE, id_opcion_registro INTEGER, id_tipo_opcion_registro INTEGER
);
CREATE TABLE IF NOT EXISTS denuncia_narracion (
    id_narracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, texto TEXT NOT NULL, diagnostico_medico TEXT, resolucion_judicial TEXT, es_flagrante BOOLEAN,
    resultado_investigacion TEXT, es_investigacion BOOLEAN NOT NULL DEFAULT FALSE, investigacion TEXT, es_analisis_criminal BOOLEAN NOT NULL DEFAULT FALSE, analisis_criminal TEXT,
    supervisor_id VARCHAR(50), supervisor_descripcion VARCHAR(200), id_usuario VARCHAR(50) NOT NULL REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(),
    editado BOOLEAN NOT NULL DEFAULT FALSE, id_usuario_edicion VARCHAR(50), fecha_hora_edicion TIMESTAMPTZ, texto_original TEXT
);
CREATE TABLE IF NOT EXISTS denuncia_equipo_trabajo (
    id_equipo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    usuario VARCHAR(50) NOT NULL REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, nombre VARCHAR(100), apellido VARCHAR(100), grado VARCHAR(100), ci VARCHAR(20), tipo INTEGER, fecha_asignado TIMESTAMPTZ NOT NULL DEFAULT now(), id_dependencia INTEGER, estado INTEGER NOT NULL DEFAULT 1
);

CREATE TABLE IF NOT EXISTS regla_tipificacion_ficha (
    id_regla BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_clasificacion INTEGER NOT NULL, tipo_denuncia VARCHAR(50),
    ficha_requerida VARCHAR(50) NOT NULL CHECK (ficha_requerida IN ('Intervinientes','Armas','Vehiculos','Objetos','Transito','Multimedias')),
    cant_minima INTEGER NOT NULL DEFAULT 0 CHECK (cant_minima >= 0), rol_persona_requerido VARCHAR(100), visible BOOLEAN NOT NULL DEFAULT TRUE, habilitada BOOLEAN NOT NULL DEFAULT TRUE,
    UNIQUE (id_clasificacion, ficha_requerida, rol_persona_requerido)
);
CREATE TABLE IF NOT EXISTS denuncia_arma (
    id_arma BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    tipo JSONB NOT NULL, marca VARCHAR(100), modelo VARCHAR(100), calibre VARCHAR(50), nro_serie VARCHAR(100), nro_registro VARCHAR(100), estado JSONB,
    avaluado_pesos NUMERIC(14,2), avaluado_dolares NUMERIC(14,2), pais_fabricante JSONB, pais_origen JSONB, pais_destino JSONB
);
CREATE TABLE IF NOT EXISTS denuncia_vehiculo (
    id_vehiculo BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    matricula VARCHAR(30), tipo JSONB, marca VARCHAR(100), modelo VARCHAR(100), color VARCHAR(50), pais JSONB, departamento JSONB, chasis VARCHAR(100), padron VARCHAR(50), anio INTEGER, propietario JSONB, aseguradora JSONB,
    avaluado_pesos NUMERIC(14,2), avaluado_dolares NUMERIC(14,2), estado JSONB, estado_global JSONB, motor VARCHAR(100), requisitoria_pendiente BOOLEAN NOT NULL DEFAULT FALSE, remolque BOOLEAN NOT NULL DEFAULT FALSE,
    luces_encendidas BOOLEAN NOT NULL DEFAULT FALSE, airbag_desplegado BOOLEAN, cilindrada INTEGER, rodado VARCHAR(50), numero_cuadro VARCHAR(100), tipo_bicicleta VARCHAR(100), luz_delantera_bicicleta BOOLEAN, luz_trasera_bicicleta BOOLEAN,
    vehiculo_policial BOOLEAN NOT NULL DEFAULT FALSE, unidad_ejecutora JSONB, unidad_ejecutora_departamento JSONB, instrumento_delito BOOLEAN NOT NULL DEFAULT FALSE, ccu JSONB, estado_al_momento JSONB, cantidad_chapas INTEGER
);
CREATE TABLE IF NOT EXISTS denuncia_vehiculo_recuperacion (
    id_recuperacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_vehiculo BIGINT NOT NULL REFERENCES denuncia_vehiculo (id_vehiculo) ON DELETE CASCADE,
    fecha_hora_recuperacion TIMESTAMPTZ, lugar_recuperacion JSONB, observaciones TEXT, id_usuario VARCHAR(50) REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, id_ampliacion_sgsp BIGINT,
    UNIQUE (id_vehiculo)
);
CREATE TABLE IF NOT EXISTS denuncia_objeto (
    id_objeto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    estado_global JSONB NOT NULL DEFAULT '[]'::jsonb, tipo_objeto JSONB, grupo JSONB, instrumento_delito BOOLEAN NOT NULL DEFAULT FALSE, circunstancia_incautacion JSONB, circunstancia_incautacion_frontera JSONB, circunstancia_incautacion_detalle TEXT, tipo_trafico JSONB,
    pais_fabricante JSONB, pais_origen JSONB, requerido BOOLEAN NOT NULL DEFAULT FALSE, atributos JSONB NOT NULL DEFAULT '[]'::jsonb, datos_recuperacion JSONB NOT NULL DEFAULT '[]'::jsonb, id_ampliacion_sgsp BIGINT, nombre_investigacion VARCHAR(255), nombre_operativo VARCHAR(255)
);
CREATE TABLE IF NOT EXISTS denuncia_transito (
    id_transito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL UNIQUE REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, tipo_siniestro VARCHAR(100), zona JSONB, jurisdiccion JSONB, estado_meteorologico JSONB, tipo_iluminacion JSONB, tipo_luz_artificial JSONB, tipo_visibilidad JSONB,
    circunstancia_conductor JSONB, circunstancia_vehiculo JSONB, circunstancia_via JSONB, circunstancia_entorno JSONB, propiedades_via_principal JSONB, propiedades_via_secundaria_1 JSONB, tipo_colision_vehiculo JSONB, tipo_colision_obstaculo JSONB, tipo_despiste JSONB, tipo_atropello_peaton JSONB, tipo_atropello_animal JSONB
);
CREATE TABLE IF NOT EXISTS denuncia_transito_persona (
    id_transito_persona BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_transito BIGINT NOT NULL REFERENCES denuncia_transito (id_transito) ON DELETE CASCADE, id_interviniente BIGINT REFERENCES denuncia_interviniente (id_interviniente) ON DELETE SET NULL,
    calidad VARCHAR(100), resultado VARCHAR(100), fecha_fallecido TIMESTAMPTZ, forma_retiro JSONB, institucion_salud JSONB, categoria_licencia JSONB, autoridad_licencia JSONB, fecha_licencia_emitida DATE, fecha_licencia_vencimiento DATE, relacion_propietario JSONB, tiempo_conduccion_previo JSONB, resultado_espirometria JSONB, ubicacion JSONB, color_ropa VARCHAR(100), lleva_elementos_seguridad BOOLEAN, usa_casco BOOLEAN, casco_reglamentado BOOLEAN, casco_abrochado BOOLEAN, lleva_cinta_chaleco BOOLEAN, cinturon_abrochado BOOLEAN, sistema_proteccion_infantil BOOLEAN, ubicacion_sistema_sri JSONB
);
CREATE TABLE IF NOT EXISTS denuncia_ampliacion (
    id_ampliacion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE,
    fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(), id_usuario VARCHAR(50) NOT NULL REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT
);
CREATE TABLE IF NOT EXISTS denuncia_ampliacion_narracion (
    id_narracion BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_ampliacion BIGINT NOT NULL REFERENCES denuncia_ampliacion (id_ampliacion) ON DELETE CASCADE, texto TEXT NOT NULL, id_usuario VARCHAR(50) REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(), supervisor_id VARCHAR(50), supervisor_descripcion VARCHAR(200), editado BOOLEAN NOT NULL DEFAULT FALSE, id_usuario_edicion VARCHAR(50), fecha_hora_edicion TIMESTAMPTZ, texto_original TEXT
);
CREATE TABLE IF NOT EXISTS denuncia_control_calidad (
    id_control BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, id_usuario VARCHAR(50) NOT NULL REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(), comentario TEXT, control_automatizado BOOLEAN NOT NULL DEFAULT FALSE, intervinientes BOOLEAN NOT NULL DEFAULT FALSE, domicilio_intervinientes BOOLEAN NOT NULL DEFAULT FALSE, domicilio_evento BOOLEAN NOT NULL DEFAULT FALSE, formato_narracion BOOLEAN NOT NULL DEFAULT FALSE, relato_narracion BOOLEAN NOT NULL DEFAULT FALSE, ortografia BOOLEAN NOT NULL DEFAULT FALSE, diagnosticos_medicos_resoluciones BOOLEAN NOT NULL DEFAULT FALSE, tipificacion BOOLEAN NOT NULL DEFAULT FALSE, objetos BOOLEAN NOT NULL DEFAULT FALSE, indicadores_estadisticos BOOLEAN NOT NULL DEFAULT FALSE, control BOOLEAN NOT NULL DEFAULT FALSE, rechazo BOOLEAN NOT NULL DEFAULT FALSE, anulacion BOOLEAN NOT NULL DEFAULT FALSE, observaciones TEXT, motivo_anulacion TEXT, id_duplicado BIGINT
);
CREATE TABLE IF NOT EXISTS denuncia_cambio (
    id_cambio BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, id_sgsp BIGINT NOT NULL REFERENCES denuncia (id_sgsp) ON DELETE CASCADE, id_respuesta BIGINT, tipo JSONB, id_usuario VARCHAR(50) REFERENCES "Usuarios" ("NombreUsuario") ON DELETE RESTRICT, fecha_hora TIMESTAMPTZ NOT NULL DEFAULT now(), comentario TEXT
);

CREATE INDEX IF NOT EXISTS ix_denuncia_estado ON denuncia (estado);
CREATE INDEX IF NOT EXISTS ix_denuncia_ubicacion_dependencia ON denuncia_ubicacion (id_dependencia);
CREATE INDEX IF NOT EXISTS ix_interviniente_denuncia ON denuncia_interviniente (id_sgsp);
CREATE INDEX IF NOT EXISTS ix_vehiculo_denuncia ON denuncia_vehiculo (id_sgsp);
CREATE INDEX IF NOT EXISTS ix_objeto_denuncia ON denuncia_objeto (id_sgsp);
CREATE INDEX IF NOT EXISTS ix_regla_tipificacion ON regla_tipificacion_ficha (id_clasificacion, tipo_denuncia);
COMMENT ON TABLE regla_tipificacion_ficha IS 'Matriz de obligatoriedad dinamica por clasificacion de denuncia.';