// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sgNetApi.Infrastructure.Data;

#nullable disable

namespace sgNetApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260824144107_IntegridadRolesPermisos")]
    partial class IntegridadRolesPermisos
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sgNetApi.Domain.Entities.AuditoriaLog", b =>
                {
                    b.Property<long>("IdLog")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdLog"));

                    b.Property<int>("CodigoEstado")
                        .HasColumnType("integer");

                    b.Property<long>("DuracionMs")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IpOrigen")
                        .IsRequired()
                        .HasMaxLength(45)
                        .HasColumnType("character varying(45)");

                    b.Property<string>("MetodoHttp")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<string>("PayloadRequest")
                        .HasColumnType("text");

                    b.Property<string>("Ruta")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("UsuarioNombreUsuario")
                        .HasColumnType("text");

                    b.HasKey("IdLog");

                    b.ToTable("AuditoriaLogs");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Dependencia", b =>
                {
                    b.Property<int>("IdDependencia")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdDependencia"));

                    b.Property<int>("IdUuee")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDependencia");

                    b.HasIndex("IdUuee");

                    b.ToTable("Dependencias");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Escalafon", b =>
                {
                    b.Property<int>("IdEscalafon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscalafon"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEscalafon");

                    b.ToTable("Escalafones");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.EstadoCivil", b =>
                {
                    b.Property<int>("IdEstadoCivil")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEstadoCivil"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEstadoCivil");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("EstadosCiviles");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrado"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGrado");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialPassword", b =>
                {
                    b.Property<long>("IdHistorialPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHistorialPassword"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioNombreUsuario")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdHistorialPassword");

                    b.HasIndex("UsuarioNombreUsuario");

                    b.ToTable("HistorialesPasswords");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialUsuario", b =>
                {
                    b.Property<long>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHistorial"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealizadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UsuarioNombreUsuario")
                        .IsRequired()
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdHistorial");

                    b.HasIndex("UsuarioNombreUsuario");

                    b.ToTable("HistorialesUsuarios");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Nacionalidad", b =>
                {
                    b.Property<int>("IdNacionalidad")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdNacionalidad"));

                    b.Property<string>("CodigoIso")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("EsUruguaya")
                        .HasColumnType("boolean");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdNacionalidad");

                    b.HasIndex("CodigoIso")
                        .IsUnique();

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Nacionalidades");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("IdPermiso");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Profesion", b =>
                {
                    b.Property<int>("IdProfesion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdProfesion"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdProfesion");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Profesiones");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Descripcion")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("IdRol");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UnidadEjecutora", b =>
                {
                    b.Property<int>("IdUuee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUuee"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUuee");

                    b.ToTable("UnidadesEjecutoras");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Celular")
                        .HasColumnType("text");

                    b.Property<long?>("Ci")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("ExpiradoPorInactividad")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateOnly>("FechaNacimiento")
                        .HasColumnType("date");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<int?>("IdDependencia")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEscalafon")
                        .HasColumnType("integer");

                    b.Property<int?>("IdEstadoCivil")
                        .HasColumnType("integer");

                    b.Property<int?>("IdGrado")
                        .HasColumnType("integer");

                    b.Property<int>("IdNacionalidad")
                        .HasColumnType("integer");

                    b.Property<int?>("IdProfesion")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("NombreUsuario");

                    b.HasIndex("Ci")
                        .IsUnique();

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("IdDependencia");

                    b.HasIndex("IdEscalafon");

                    b.HasIndex("IdEstadoCivil");

                    b.HasIndex("IdGrado");

                    b.HasIndex("IdNacionalidad");

                    b.HasIndex("IdProfesion");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.HasKey("NombreUsuario", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("UsuarioPermiso");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<string>("NombreUsuario")
                        .HasColumnType("character varying(50)");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("NombreUsuario", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Dependencia", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.UnidadEjecutora", "UnidadEjecutora")
                        .WithMany()
                        .HasForeignKey("IdUuee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadEjecutora");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialPassword", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialPasswords")
                        .HasForeignKey("UsuarioNombreUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialUsuario", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioNombreUsuario")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("IdDependencia")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("sgNetApi.Domain.Entities.Escalafon", "Escalafon")
                        .WithMany()
                        .HasForeignKey("IdEscalafon");

                    b.HasOne("sgNetApi.Domain.Entities.EstadoCivil", "EstadoCivil")
                        .WithMany()
                        .HasForeignKey("IdEstadoCivil");

                    b.HasOne("sgNetApi.Domain.Entities.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("IdGrado");

                    b.HasOne("sgNetApi.Domain.Entities.Nacionalidad", "Nacionalidad")
                        .WithMany("Usuarios")
                        .HasForeignKey("IdNacionalidad")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Profesion", "Profesion")
                        .WithMany()
                        .HasForeignKey("IdProfesion");

                    b.Navigation("Dependencia");

                    b.Navigation("Escalafon");

                    b.Navigation("EstadoCivil");

                    b.Navigation("Grado");

                    b.Navigation("Nacionalidad");

                    b.Navigation("Profesion");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Permiso", "Permiso")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("NombreUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("NombreUsuario")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Nacionalidad", b =>
                {
                    b.Navigation("Usuarios");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("HistorialPasswords");

                    b.Navigation("Historiales");

                    b.Navigation("UsuarioPermisos");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
