// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using sgNetApi.Infrastructure.Data;

#nullable disable

namespace sgNetApi.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260811145000_MigracionInicial")]
    partial class MigracionInicial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("sgNetApi.Domain.Entities.Dependencia", b =>
                {
                    b.Property<int>("IdDependencia")
                        .HasColumnType("integer");

                    b.Property<int>("IdUuee")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdDependencia", "IdUuee");

                    b.HasIndex("IdUuee");

                    b.ToTable("Dependencias");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Escalafon", b =>
                {
                    b.Property<int>("IdEscalafon")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdEscalafon"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdEscalafon");

                    b.ToTable("Escalafones");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Grado", b =>
                {
                    b.Property<int>("IdGrado")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdGrado"));

                    b.Property<string>("Abreviatura")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Numero")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdGrado");

                    b.ToTable("Grados");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialPassword", b =>
                {
                    b.Property<long>("IdHistorialPassword")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHistorialPassword"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<long>("UsuarioCi")
                        .HasColumnType("bigint");

                    b.HasKey("IdHistorialPassword");

                    b.HasIndex("UsuarioCi");

                    b.ToTable("HistorialesPasswords");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialUsuario", b =>
                {
                    b.Property<long>("IdHistorial")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("IdHistorial"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observaciones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RealizadoPor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TipoAccion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("UsuarioCi")
                        .HasColumnType("bigint");

                    b.HasKey("IdHistorial");

                    b.HasIndex("UsuarioCi");

                    b.ToTable("HistorialesUsuarios");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Permiso", b =>
                {
                    b.Property<int>("IdPermiso")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdPermiso"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdPermiso");

                    b.ToTable("Permisos");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Rol", b =>
                {
                    b.Property<int>("IdRol")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdRol"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdRol");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.RolPermiso", b =>
                {
                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.HasKey("IdRol", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("RolPermiso");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UnidadEjecutora", b =>
                {
                    b.Property<int>("IdUuee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IdUuee"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Siglas")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IdUuee");

                    b.ToTable("UnidadesEjecutoras");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.Property<long>("Ci")
                        .HasColumnType("bigint");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<long>("Celular")
                        .HasColumnType("bigint");

                    b.Property<string>("Correo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Creado")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("EscalafonIdEscalafon")
                        .HasColumnType("integer");

                    b.Property<bool>("ExpiradoPorInactividad")
                        .HasColumnType("boolean");

                    b.Property<int>("GradoIdGrado")
                        .HasColumnType("integer");

                    b.Property<bool>("Habilitado")
                        .HasColumnType("boolean");

                    b.Property<int>("IdDependencia")
                        .HasColumnType("integer");

                    b.Property<int>("IdEscalafon")
                        .HasColumnType("integer");

                    b.Property<int>("IdGrado")
                        .HasColumnType("integer");

                    b.Property<int>("IdUuee")
                        .HasColumnType("integer");

                    b.Property<int>("IntentosFallidos")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreUsuario")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea");

                    b.Property<DateTime?>("UltimoAcceso")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("UnidadEjecutoraIdUuee")
                        .HasColumnType("integer");

                    b.HasKey("Ci");

                    b.HasIndex("Correo")
                        .IsUnique();

                    b.HasIndex("EscalafonIdEscalafon");

                    b.HasIndex("GradoIdGrado");

                    b.HasIndex("UnidadEjecutoraIdUuee");

                    b.HasIndex("IdDependencia", "IdUuee");

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.Property<long>("UsuarioCi")
                        .HasColumnType("bigint");

                    b.Property<int>("IdPermiso")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioCi", "IdPermiso");

                    b.HasIndex("IdPermiso");

                    b.ToTable("UsuarioPermiso");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioRol", b =>
                {
                    b.Property<long>("UsuarioCi")
                        .HasColumnType("bigint");

                    b.Property<int>("IdRol")
                        .HasColumnType("integer");

                    b.HasKey("UsuarioCi", "IdRol");

                    b.HasIndex("IdRol");

                    b.ToTable("UsuarioRol");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Dependencia", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.UnidadEjecutora", "UnidadEjecutora")
                        .WithMany()
                        .HasForeignKey("IdUuee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UnidadEjecutora");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialPassword", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("HistorialPasswords")
                        .HasForeignKey("UsuarioCi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.HistorialUsuario", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Historiales")
                        .HasForeignKey("UsuarioCi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.RolPermiso", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Permiso", "Permiso")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Rol", "Rol")
                        .WithMany("RolPermisos")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Rol");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Escalafon", "Escalafon")
                        .WithMany()
                        .HasForeignKey("EscalafonIdEscalafon")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Grado", "Grado")
                        .WithMany()
                        .HasForeignKey("GradoIdGrado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.UnidadEjecutora", "UnidadEjecutora")
                        .WithMany()
                        .HasForeignKey("UnidadEjecutoraIdUuee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Dependencia", "Dependencia")
                        .WithMany()
                        .HasForeignKey("IdDependencia", "IdUuee")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dependencia");

                    b.Navigation("Escalafon");

                    b.Navigation("Grado");

                    b.Navigation("UnidadEjecutora");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioPermiso", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Permiso", "Permiso")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("IdPermiso")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioPermisos")
                        .HasForeignKey("UsuarioCi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Permiso");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.UsuarioRol", b =>
                {
                    b.HasOne("sgNetApi.Domain.Entities.Rol", "Rol")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("IdRol")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("sgNetApi.Domain.Entities.Usuario", "Usuario")
                        .WithMany("UsuarioRoles")
                        .HasForeignKey("UsuarioCi")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Rol");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Permiso", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioPermisos");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Rol", b =>
                {
                    b.Navigation("RolPermisos");

                    b.Navigation("UsuarioRoles");
                });

            modelBuilder.Entity("sgNetApi.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("HistorialPasswords");

                    b.Navigation("Historiales");

                    b.Navigation("UsuarioPermisos");

                    b.Navigation("UsuarioRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
